beans:
    path: .beans
    prefix: prometheus-vcgencmd-
    id_length: 4
    default_status: todo
    default_type: task
    git:
        enabled: true
        auto_create_branch: true
        auto_commit_beans: true
        base_branch: main
        require_merge: true
